FROM ubuntu:latest

FROM python:3.8.10

WORKDIR /app

RUN pip install pytest
RUN pip install pytest requests 
RUN pip install pytest-html
RUN pip install pytest pytest-html

COPY . .
RUN pip install -r requirement.txt
CMD ["pytest" ,"test_api.py","--html=report.html"]
